fix: windows specific line ending characters (#14)
* Fix line-ending incompatibility bug

Orbital symmetry comparison check failed on Linux because of Windows-style line endings in text file
AssertionError: assert ['A1g\r', 'A1...'E1uy\r', ...] == ['A1g', 'A1u'..., 'E1uy', ...].

* test: add cross-platform ci

* fix: race condition

---------

Co-authored-by: Kalman Szenes <szenes.kalman@gmail.com>